<?php

namespace Easy\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository 
{
    public function selectNbMessagesSujet() 
    {
        $stmt = $this->getEntityManager()  
               ->getConnection()  
               ->prepare('SELECT sujet_id AS sujet, COUNT(*) AS nbMessages FROM message GROUP BY sujet_id');  
        $stmt->execute();  
        return $stmt->fetchAll(); 
    }
}
