<?php

namespace Easy\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository 
{
    // TODO : A recoder en DQL
    public function selectNbMessagesSujet() 
    {
        $stmt = $this->getEntityManager()  
               ->getConnection()  
               ->prepare('SELECT sujet_id AS sujet, COUNT(*) AS nbMessages FROM message GROUP BY sujet_id');  
        $stmt->execute();  
        return $stmt->fetchAll(); 
    }
    
    // TODO : A recoder en DQL
    public function selectNbMessagesForum() 
    {
        $stmt = $this->getEntityManager()  
               ->getConnection()  
               ->prepare('SELECT s.forum_id AS forum, COUNT(*) AS nbMessages FROM message m '
                       . 'INNER JOIN sujet s ON m.sujet_id = s.id '
                       . 'GROUP BY s.forum_id');  
        $stmt->execute();  
        return $stmt->fetchAll(); 
    }
    
    public function getDernierMessageForum()
    {
        
    }
}
