<?php

namespace Easy\DonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonRepository extends EntityRepository
{
    /*
     * Renvoie la moyenne des dons pour un utilisateur
     */
    public function findMoyenneUtilisateur($utilisateur)
    {
        $requete = $this->createQueryBuilder('d')
                    ->select('AVG(d.montant)')
                    ->where('d.utilisateur='.$utilisateur->getId())
                    ->getQuery()
                    ->getSingleScalarResult();
        
        return $requete;
    }
    
   /*
     * 
     */
    public function findDonsPourUnMois($date)
    {        
        return 0;
    } 
    
    /*
     * Statistiques
     */
    public function selectStatistiquesGlobales()
    {
        
    }
}
