<?php

namespace Easy\DonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonRepository extends EntityRepository
{
    /*
     * Renvoie le total des dons effectué pour un utilisateur
     */
    public function findTotal($utilisateur)
    {
        
    }
    
    /*
     * Statistiques
     */
    public function selectStatistiquesGlobales()
    {
        
    }
    
    /*
     * Sélectionne l'ensenble des dons effectués par utilisateur et par mois
     */
    public function selectDonParMois()
    {
        
    }
}
